### ISSUE TITLE
Implement Geomark Properties class.

### ISSUE THREAD

**Issue by spatialbits** [greg-and-adam/python-geomark#11]
I propose we implement a Geomark Properties class that stores all the handy metadata that we can get about a particular geomark.

Eg. Make the following GET: [http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuvwxyz0000bc.json](http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuvwxyz0000bc.json) (see the response below) and we get a slew of informative properties that would be very useful to the user. The response is 40Kb-ish so it isn't tiny, but I believe worthwhile to have. I believe for now we could ignore the resource links that it provides.

I propose we instantiate a GeomarkProperties class and store on the Geomark instance when the Geomark is instantiated with a `geomarkId`. It would mean the data is pulled on every instantiation of a Geomark and would improve the richness of the Geomark class but at the cost of performance. 

See the response:
```
{
  "id":"gm-abcdefghijklmnopqrstuvwxyz0000bc",
  "url":"http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuvwxyz0000bc",
  "geometryType":"Polygon",
  "numPolygons":1,
  "numParts":1,
  "createDate":"2011-05-12",
  "expiryDate":null,
  "minX":-144.66493120016213,
  "minY":47.527035309509756,
  "maxX":-112.98918590637564,
  "maxY":60.724742238714434,
  "centroidX":-128.10446766729424,
  "centroidY":54.74533227390394,
  "numVertices":13,
  "length":5958503.516035516,
  "area":1878642016189,
  "isValid":true,
  "validationError":null,
  "isSimple":true,
  "isRobust":true,
  "minimumClearance":94994.294,
  "googleMapsUrl":"http://maps.google.ca/?q=http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuvwxyz0000bc/parts.kml",
  "googleEarthUrl":"http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuvwxyz0000bc/parts.kml",
  "resourceLinks":[
    {
      "title":"Info HTML  representation of Geomark gm-abcdefghijklmnopqrstuvwxyz0000bc",
      "href":"http://apps.gov.bc.ca/pub/geomark/geomarks/gm-abcdefghijklmnopqrstuvwxyz0000bc",
      "resource":"info",
      "format":"xhtml",
      "mediaType":"application/xhtml+xml"
    },
    ...
  ]
}
```

**Comment by spatialbits** [comment]
The alternative to instantiating the properties on a Geomark instantiation would be to add a `get_properties()` method to the `Geomark` class.

**Comment by gregseb** [comment]
Are you proposing that we remove the ability to choose which API routine to call and just have it all called together in order to fully populate this properties object?

I think I might be more in favour of using lazy loading.   So when you attempt to access a property it checks if it exists, and if not, call the relevant API routine.

**Comment by spatialbits** [comment]
Nope. All those properties comes from one call to the base geomark api url, they don't include results to api methods such as `point`, `feature`, etc. It's just helpful metadata about the geomark. It has some info that _could_ come from an api call, like `bbox` or `point`, but the api methods provide more detail, projections, formats, that this won't.

**Comment by gregseb** [comment]
Ah, I see you mean the .info() call.  We are already including info as a call that can be used, so I don't really see why make it too smart.  Maybe lets keep this system dumb for now and circle back to this when we're happy with the basic functionality and structure?

**Comment by spatialbits** [comment]
Uh, yeah that _is_ the `info` method. Yeah we can leave it.
