### ISSUE TITLE
Build up an overridable config system

### ISSUE THREAD

**Issue by gregseb** [greg-and-adam/python-geomark#6]
We will need a basic config system that stores config in some sort of container.  Perhaps in an object or simply a dictionary?

**Comment by gregseb** [comment]
@spatialbits Ideas?

**Comment by spatialbits** [comment]
@gregseb can you describe a little what you are thinking the config system should manage and how it would cooperate with the geomark module?

**Comment by gregseb** [comment]
Anything that could possibly change in the future, and a debug setting.

So at the top of my head.... the base_url and debug.   Chances are base_url will likely never change.  But it *could* and although I'd like to say we'll be plenty fast enough to update the code we might not be fast enough for someone, so to be safe we should just declare it as a config option.  Plus its a convenient way to keep it somewhere easily accessible by any other modules we create.

**Comment by spatialbits** [comment]
Nice work @gregseb
