### ISSUE TITLE
Implement "feature"

### ISSUE THREAD

**Issue by gregseb** [greg-and-adam/python-geomark#7]
While we're at it, this might be a good place to make sure we can handle all the projections supported by Geomark in a way that's reusable with all the other methods.

**Comment by spatialbits** [comment]
This has been sketched in, along with the other api methods with the exception of COPY and CREATE. I suggest we pause on this while we come up with a general strategy for fetching/transforming request data.

**Comment by spatialbits** [comment]
Closing this for now
